"use client";

import Image from "next/image";
import { useEffect, useState } from "react";
import {
  Search,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  SlidersHorizontal,
  Calendar,
  Eye,
  Download,
  MoreVertical,
} from "lucide-react";
import {
  kundaliTypeStyles,
  statusStyles,
  doshaStyles,
} from "./data";
import { api } from "../../../lib/api";

function fmtKD(iso: string) {
  if (!iso) return { date: "", time: "" };
  const d = new Date(iso);
  return {
    date: d.toLocaleDateString("en-GB", { day: "2-digit", month: "short", year: "numeric" }),
    time: d.toLocaleTimeString("en-US", { hour: "2-digit", minute: "2-digit", hour12: true }),
  };
}

const tabs = [
  { label: "All Kundali", active: true },
  { label: "Today's Kundali" },
  { label: "Pending" },
  { label: "Completed" },
  { label: "AI Interpretation" },
  { label: "Doshas" },
  { label: "Archived" },
];

const selects = [
  { value: "All Astrologers", w: "w-[126px]" },
  { value: "All Kundali Types", w: "w-[122px]" },
  { value: "All Status", w: "w-[108px]" },
];

const headers: { label: string; cls: string }[] = [
  { label: "Kundali ID", cls: "w-[72px] text-left" },
  { label: "Client Details", cls: "w-[123px] text-left" },
  { label: "Kundali Type", cls: "w-[90px] text-left" },
  { label: "Generated By", cls: "w-[131px] text-center" },
  { label: "Date & Time", cls: "w-[84px] text-left" },
  { label: "Status", cls: "w-[65px] text-center" },
  { label: "Doshas", cls: "w-[107px] text-center" },
  { label: "Amount", cls: "w-[63px] text-left" },
];

function Checkbox() {
  return (
    <span className="block h-[11px] w-[11px] rounded-[3px] border border-[#CFCBDB] bg-white" />
  );
}

export default function KundaliPanel() {
  const [list, setList] = useState<any[] | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState("");
  const [total, setTotal] = useState(0);

  useEffect(() => {
    api.admin
      .getReports()
      .then((data: any) => {
        const items = data?.data ?? data ?? [];
        if (data?.meta?.total) setTotal(data.meta.total);
        const rows = items.filter((r: any) =>
          (r.type || "").toLowerCase().includes("kundli") ||
          (r.type || "").toLowerCase().includes("kundali")
        );
        const src = rows.length ? rows : items;
        if (src.length) {
          setList(
            src.map((r: any) => {
              const { date, time } = fmtKD(r.created_at);
              return {
                id: `KNDL-${r.id}`,
                client: { name: r.title || "Client", email: "", phone: "" },
                type: "janam",
                astrologer: {
                  name: "Astrologer",
                  role: "Vedic Expert",
                  avatar: "",
                },
                date,
                time,
                status: "completed",
                dosha: null,
                amount: "-",
                payment: "Paid",
              };
            })
          );
        }
      })
      .catch((e) => setError(e.message))
      .finally(() => setLoading(false));
  }, []);

  const kundaliRows = list || [];

  if (loading) return <div className="flex justify-center py-10"><svg className="h-6 w-6 animate-spin text-[#7C3AED]" viewBox="0 0 24 24" fill="none"><circle cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4" strokeDasharray="32" strokeLinecap="round" /></svg></div>;
  if (error) return <div className="flex justify-center py-10 text-[#EF4444] text-[13px]">{error}</div>;

  return (
    <section>
      {/* Tabs */}
      <div className="no-scrollbar flex items-center overflow-x-auto pl-[8px]">
        {tabs.map((t) => (
          <button
            key={t.label}
            type="button"
            className={`shrink-0 whitespace-nowrap border-b-[3px] px-[18px] pb-[11px] pt-[15px] text-[12px] leading-[18px] ${
              t.active
                ? "border-[#4208D1] font-semibold text-[#3A0FD1]"
                : "border-transparent font-medium text-[#2B2B55] hover:text-[#3A0FD1]"
            }`}
          >
            {t.label}
          </button>
        ))}
      </div>

      <div className="rounded-[12px] border border-[#F0F1F5] bg-white shadow-[0_1px_2px_rgba(24,20,40,.03)]">
        {/* Filters */}
        <div className="no-scrollbar flex flex-nowrap items-center gap-[13px] overflow-x-auto px-[13px] pt-[24px]">
          <div className="flex h-[33px] w-[198px] shrink-0 items-center gap-[6px] rounded-[8px] border border-[#ECEEF3] bg-white pl-[13px] pr-[12px]">
            <input
              type="text"
              placeholder="Search by name, email or phone..."
              className="h-full w-full bg-transparent text-[10px] text-[#2E2A3B] outline-none placeholder:text-[#9B9AAC]"
            />
            <Search size={15} className="shrink-0 text-[#1E1B5C]" />
          </div>

          {selects.map((s) => (
            <button
              key={s.value}
              type="button"
              className={`flex h-[33px] ${s.w} shrink-0 items-center justify-between whitespace-nowrap rounded-[8px] border border-[#ECEEF3] bg-white pl-[11px] pr-[9px] text-[10px] font-semibold text-[#14134A]`}
            >
              {s.value}
              <ChevronDown size={14} className="shrink-0 text-[#6E6A85]" />
            </button>
          ))}

          <button
            type="button"
            className="flex h-[33px] w-[162px] shrink-0 items-center justify-between whitespace-nowrap rounded-[8px] border border-[#ECEEF3] bg-white pl-[11px] pr-[9px] text-[10px] font-semibold text-[#14134A]"
          >
            <span>
              01 May 2025&nbsp;&nbsp;·&nbsp;&nbsp;18 May 2025
            </span>
            <Calendar size={14} className="shrink-0 text-[#6D28D9]" />
          </button>

          <button
            type="button"
            className="inline-flex h-[33px] w-[66px] shrink-0 items-center justify-center gap-[5px] rounded-[8px] border border-[#ECEEF3] bg-white text-[10px] font-semibold text-[#14134A]"
          >
            <SlidersHorizontal size={13} className="text-[#4A4869]" />
            Filters
          </button>
        </div>

        {/* Table */}
        <div className="mt-[20px] overflow-x-auto">
          <table className="w-full min-w-[840px] table-fixed border-collapse">
            <colgroup>
              <col className="w-[45px]" />
              <col className="w-[72px]" />
              <col className="w-[123px]" />
              <col className="w-[90px]" />
              <col className="w-[131px]" />
              <col className="w-[84px]" />
              <col className="w-[65px]" />
              <col className="w-[107px]" />
              <col className="w-[63px]" />
              <col className="w-[98px]" />
            </colgroup>

            <thead>
              <tr className="h-[45px] bg-[#FBFBFD]">
                <th className="pl-[18px] text-left align-middle">
                  <Checkbox />
                </th>
                {headers.map((h) => (
                  <th
                    key={h.label}
                    className={`whitespace-nowrap align-middle text-[10px] font-semibold text-[#14134A] ${h.cls}`}
                  >
                    {h.label}
                  </th>
                ))}
                <th className="pr-[20px] text-center align-middle text-[10px] font-semibold text-[#14134A]">
                  Actions
                </th>
              </tr>
            </thead>

            <tbody>
              {kundaliRows.map((k) => {
                const type = kundaliTypeStyles[k.type];
                const st = statusStyles[k.status];
                const dosha = k.dosha ? doshaStyles[k.dosha] : null;

                return (
                  <tr key={k.id} className="h-[61px] border-b border-[#F4F4F8]">
                    <td className="pl-[18px] align-middle">
                      <Checkbox />
                    </td>

                    <td className="whitespace-nowrap align-middle text-[11px] font-semibold text-[#3D17C9]">
                      {k.id}
                    </td>

                    <td className="pr-[6px] align-middle">
                      <p className="whitespace-nowrap text-[11px] font-bold leading-[15.5px] text-[#14134A]">
                        {k.client.name}
                      </p>
                      <p className="whitespace-nowrap text-[9.5px] leading-[15.5px] text-[#8B879C]">
                        {k.client.email}
                      </p>
                      <p className="whitespace-nowrap text-[9.5px] leading-[15.5px] text-[#8B879C]">
                        {k.client.phone}
                      </p>
                    </td>

                    <td className="align-middle">
                      <span
                        className={`inline-flex h-[17px] items-center whitespace-nowrap rounded-[6px] px-[6px] text-[9.5px] font-medium ${type.bg} ${type.text}`}
                      >
                        {type.label}
                      </span>
                    </td>

                    <td className="align-middle">
                      <div className="flex items-center gap-[10px]">
                        <Image
                          src={k.astrologer.avatar}
                          alt={k.astrologer.name}
                          width={26}
                          height={26}
                          className="h-[26px] w-[26px] shrink-0 rounded-full object-cover"
                        />
                        <div>
                          <p className="whitespace-nowrap text-[11px] font-bold leading-[16px] text-[#14134A]">
                            {k.astrologer.name}
                          </p>
                          <p className="whitespace-nowrap text-[10px] leading-[15px] text-[#8B879C]">
                            {k.astrologer.role}
                          </p>
                        </div>
                      </div>
                    </td>

                    <td className="align-middle">
                      <p className="whitespace-nowrap text-[11px] leading-[16px] text-[#2E2A3B]">
                        {k.date}
                      </p>
                      <p className="whitespace-nowrap text-[11px] leading-[16px] text-[#2E2A3B]">
                        {k.time}
                      </p>
                    </td>

                    <td className="text-center align-middle">
                      <span
                        className={`inline-flex h-[17px] items-center whitespace-nowrap rounded-[6px] px-[8px] text-[9.5px] font-medium ${st.bg} ${st.text}`}
                      >
                        {st.label}
                      </span>
                    </td>

                    <td className="text-center align-middle">
                      {dosha ? (
                        <span
                          className={`inline-flex h-[17px] items-center whitespace-nowrap rounded-[6px] px-[8px] text-[9.5px] font-medium ${dosha.bg} ${dosha.text}`}
                        >
                          {dosha.label}
                        </span>
                      ) : (
                        <span className="text-[11px] text-[#4A4D89]">-</span>
                      )}
                    </td>

                    <td className="align-middle">
                      <p className="whitespace-nowrap text-[11px] font-bold leading-[16px] text-[#14134A]">
                        {k.amount}
                      </p>
                      <p
                        className={`whitespace-nowrap text-[10px] font-medium leading-[15px] ${
                          k.payment === "Paid"
                            ? "text-[#16A34A]"
                            : "text-[#F28C1E]"
                        }`}
                      >
                        {k.payment}
                      </p>
                    </td>

                    <td className="pr-[20px] align-middle">
                      <div className="flex items-center justify-center gap-[3px]">
                        <button
                          type="button"
                          aria-label="View"
                          className="grid h-[22px] w-[24px] place-items-center rounded-[6px] border border-[#ECEEF3] bg-white text-[#4A5085] hover:bg-[#FAF9FC]"
                        >
                          <Eye size={13} />
                        </button>
                        <button
                          type="button"
                          aria-label="Download"
                          className="grid h-[22px] w-[24px] place-items-center rounded-[6px] border border-[#ECEEF3] bg-white text-[#4A5085] hover:bg-[#FAF9FC]"
                        >
                          <Download size={13} />
                        </button>
                        <button
                          type="button"
                          aria-label="More"
                          className="grid h-[22px] w-[24px] place-items-center rounded-[6px] border border-[#ECEEF3] bg-white text-[#4A5085] hover:bg-[#FAF9FC]"
                        >
                          <MoreVertical size={13} />
                        </button>
                      </div>
                    </td>
                  </tr>
                );
              })}
            </tbody>
          </table>
        </div>

        {/* Pagination */}
        <div className="flex flex-wrap items-center gap-4 px-[20px] py-[13px]">
          <p className="text-[12px] font-semibold text-[#14133F]">
            Showing 1 to 10 of {(total || kundaliRows.length).toLocaleString("en-IN")} kundalis
          </p>

          <div className="mx-auto flex items-center gap-[6px]">
            <button
              type="button"
              aria-label="Previous"
              className="grid h-[30px] w-[30px] place-items-center rounded-[8px] border border-[#ECEEF3] bg-white text-[#4A4869]"
            >
              <ChevronLeft size={15} />
            </button>

            <button
              type="button"
              className="grid h-[30px] w-[30px] place-items-center rounded-[8px] bg-gradient-to-b from-[#350687] to-[#2B0372] text-[11.5px] font-semibold text-white"
            >
              1
            </button>

            {["2", "3", "4", "5"].map((p) => (
              <button
                key={p}
                type="button"
                className="grid h-[30px] w-[30px] place-items-center rounded-[8px] border border-[#ECEEF3] bg-white text-[11.5px] font-medium text-[#14134A]"
              >
                {p}
              </button>
            ))}

            <span className="grid h-[30px] w-[30px] place-items-center rounded-[8px] border border-[#ECEEF3] bg-white text-[11.5px] text-[#8B879C]">
              ...
            </span>

            <button
              type="button"
              className="grid h-[30px] w-[38px] place-items-center rounded-[8px] border border-[#ECEEF3] bg-white text-[11.5px] font-medium text-[#14134A]"
            >
              569
            </button>

            <button
              type="button"
              aria-label="Next"
              className="grid h-[30px] w-[30px] place-items-center rounded-[8px] border border-[#ECEEF3] bg-white text-[#4A4869]"
            >
              <ChevronRight size={15} />
            </button>
          </div>

          <button
            type="button"
            className="flex h-[30px] w-[101px] items-center justify-between rounded-[8px] border border-[#ECEEF3] bg-white pl-[12px] pr-[10px] text-[11.5px] font-semibold text-[#14134A]"
          >
            10 / page
            <ChevronDown size={15} className="shrink-0 text-[#6E6A85]" />
          </button>
        </div>
      </div>
    </section>
  );
}
